### ISSUE TITLE
AbstractContentProvider.java:40 (com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.michenux.drodrolib.MCXApplication)

### ISSUE THREAD

**Issue by jelqui** [Michenux/YourAppIdea#21]
04-30 04:14:52.968 16075-16075/org.michenux.yourappidea.debug D/AndroidRuntime: Shutting down VM
04-30 04:14:52.971 16075-16075/org.michenux.yourappidea.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: org.michenux.yourappidea.debug, PID: 16075
                                                                                java.lang.RuntimeException: Unable to get provider org.michenux.yourappidea.aroundme.PlaceContentProvider: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.michenux.drodrolib.MCXApplication
                                                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5156)
                                                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
                                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                **_ Caused by: java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to org.michenux.drodrolib.MCXApplication_**
                                                                                    at org.michenux.drodrolib.db.AbstractContentProvider.onCreate(**AbstractContentProvider.java:40**)
                                                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
                                                                                    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
                                                                                    at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
                                                                                    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748) 
                                                                                    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688) 
                                                                                    at android.app.ActivityThread.-wrap1(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by hopewise** [comment]
Did you solve this problem?

**Comment by Michenux** [comment]
Hi,

Not tried but it seems the problem is about "Instant Run" in Android Studio.
Two solutions there:
[(http://stackoverflow.com/questions/36495954/bootstrapapplication-cannot-be-cast-to-applicationclass)]

**Comment by hopewise** [comment]
Thank you, disabling Instant Run solved the issue! but it stopped me for 6 days 😢  , I think its a good idea to mention this possible issue at the ReadMe for other users ..
